### ISSUE TITLE
module 'easyclimate' has no attribute 'calc_detrend_data'

### ISSUE THREAD

**Issue by yangxianke** [shenyulu/easyclimate#56]
I can't use the function under ecl, it always shows errors

> `AttributeError: module 'easyclimate' has no attribute 'calc_detrend_data'`

This is my simple code：
```
import easyclimate as ecl
CRU_tmean_ano_trend1 = ecl.calc_detrend_data(CRU_tmean_ano, dim = 'time')
```

when I try others functions, it also shows same errors.

> AttributeError: module 'easyclimate' has no attribute 'open_tutorial_dataset'

**Comment by shenyulu** [comment]
Hi! I don't know what your platform is? Both Windows and Linux should be able to directly reference this method. You can use `ecl.stat.calc_detrend_data` and `ecl.tutorial.open_tutorial_dataset` for temporary use.
